import {memo} from 'react';
import type {NextPage, GetServerSidePropsContext} from 'next'
import Head from "next/head";
import {NotFound} from "@/components/NotFound/NotFound";

type TUserInfoPage = {
    userId: string;
    id: number;
    avatar_url: string;
    login: number;
    email: string;
    location: string;
    created_at: string;
    message: string;
}

const UserInfoPage: NextPage<TUserInfoPage> = memo((props) => {
    const {id, message, avatar_url, login, email, location, created_at, userId} = props;
    const isDataNotFound = !message;

    return (
        <div>
            <Head>
                <title>Information about user with id: {id}</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <div>
                {isDataNotFound ?
                    <ul style={{listStyle: 'none'}}>
                        <li>
                            <img src={avatar_url} alt="avatar" width={250} height={250}/>
                        </li>
                        <li>
                            Login: {login}
                        </li>
                        <li>
                            Email: {email ? email : 'sorry, email address is not indicated'}
                        </li>

                        <li>
                            Location: {location ? location : 'sorry, location is not indicated'}
                        </li>
                        <li>
                            Created account: {created_at}
                        </li>
                    </ul>
                    :
                    <NotFound userId={userId}/>}
            </div>
        </div>
    )
});

UserInfoPage.displayName = 'UserInfoPage'

export async function getServerSideProps(context: GetServerSidePropsContext) {
    const {userId} = context.query;

    const data = await fetch(`https://api.github.com/users/${userId}`,
        {
            method: 'GET'
        }
    );

    const userData = await data.json();

    return {
        props: userData
    }
}

export default UserInfoPage;