import type { NextPage } from 'next'
import Head from 'next/head'
import { Button } from '@/components/button'

const Home: NextPage = (props: any) => {
  return (
    <div>
      <Head>
        <title>props.userData.props</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        { props.userData.login }
      </div>
      <Button />
      <img src={ props.userData.avatar_url } alt="" />
    </div>
  )
}

export async function getServerSideProps(context: any) {
  const result = await fetch(`https://api.github.com/users/${context.query.userId}`, {
    method: 'GET',
  })

  const userData = await result.json();

  return {
    props: {
      userData,
    },
  }
}

export default Home
