import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

const Home: NextPage = (props: any) => {
  console.log('props:', props);
  return (
    <div>
      <Head>
        <title>props.userData.props</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        { props.userData.login }
      </div>
      <img src={ props.userData.avatar_url } alt="" />
    </div>
  )
}

export async function getStaticProps(context: any) {

  const result = await fetch(`https://api.github.com/users/hydrock`, {
    method: 'GET',
  })

  const userData = await result.json();

  return {
    props: {
      userData,
    },
  }
}

export default Home
